- hosts: 127.0.0.1
  become: true
  pre_tasks:
    - name: update repositories
      apt:
            update_cache=yes
            upgrade=dist # to resolve the warning message "Could not find aptitude. Using apt-get instead"
      changed_when: False

  tasks:
    - name: ubuntu pakcage install upgrade
      include: tasks/packages.yml
      tags: finished

    - name: install R
      include: tasks/installR.yml
      tags: finished

    - name: install RStudio
      include: tasks/installRstudio.yml
      tags: finished

    - name: install slack
      include: tasks/installSlack.yml
      tags: finished

    - name: install chrome
      include: tasks/installChrome.yml
      tags: finished

    - name: install atom
      include: tasks/installAtom.yml
      tags: finished

    - name: install r dependencies
      include: tasks/installRdependencies.yml
      tags: finished

    - name: install insync
      include: tasks/installInsync.yml
      tags: finished

    - name: install Google Earth
      include: tasks/installGoogleEarth.yml
      tags: finished

    - name: install QGIS
      include: tasks/installQGIS.yml
      tags: unfinished
