- name: Add QGIS key
  command: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CAEB3DC3BDF7FB45

- name: Add QGIS key step 2
  command: gpg --export --armor CAEB3DC3BDF7FB45 | sudo apt-key add -

- name: Add QGIS repo
  apt_repository:
    repo: 'deb https://qgis.org/ubuntugis bionic main'
    state: present
    update_cache: yes

- name: Add QGIS src repo
  apt_repository:
    repo: 'deb-src https://qgis.org/ubuntugis bionic main'
    state: present
    update_cache: yes

- name: Add QGIS src repo
  apt_repository:
    repo: 'ppa:ubuntugis/ubuntugis-unstable'
    state: present
    update_cache: yes

- name: Install QGIS and related packages
  apt: pkg={{item}} state=latest update_cache=yes
  with_items:
    - qgis
    - python-qgis
    - qgis-plugin-grass


# https://github.com/qgis/QGIS-Website/issues/462
# https://gis.stackexchange.com/questions/276539/installing-qgis3-on-ubuntu-16-04-xenial-dependency-problem
